import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

import { api } from "~/utils/api";

export default function Home() {
  const [pessoas, setPessoas] = useState([{ nome: "marcelo", n_vezes: 20 }]);
  const [inputValue, setInputValue] = useState(""); // State for the input value

  const handleInputChange = (event) => {
    setInputValue(event.target.value);
  };

  const handleAddPessoa = () => {
    const newPessoa = { nome: inputValue, n_vezes: 0 };
    setPessoas([...pessoas, newPessoa]);
    setInputValue(""); // Clear the input field
  };

  const handleDeletePessoa = (index) => {
    const updatedPessoas = [...pessoas];
    updatedPessoas.splice(index, 1);
    setPessoas(updatedPessoas);
  };

  const handleIncrementVezes = (index:any) => {
    const updatedPessoas = [...pessoas];
    updatedPessoas[index].n_vezes++;
    setPessoas(updatedPessoas);
  };

  const handleDecrementVezes = (index) => {
    const updatedPessoas = [...pessoas];
    if (updatedPessoas[index].n_vezes > 0) {
      updatedPessoas[index].n_vezes--;
      setPessoas(updatedPessoas);
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="h-20 bg-green-600 p-4 ">
        <Image alt="logo" src={"/nb.svg"} width={200} height={100} />
      </header>
      <main className="flex min-h-screen   flex-col items-center bg-gradient-to-b ">
        <div className="w-1/2">
          <div className="py-5" />
          <div className="flex flex-col gap-2">
            <label className="text-3xl font-bold">
              Insira o nome do Cliente:
            </label>
            <input
              type="text"
              className="rounded-md border p-2"
              value={inputValue}
              onChange={handleInputChange}
              placeholder="Nome"
            />
            <button
              onClick={handleAddPessoa}
              className="rounded bg-blue-500 px-4 py-2 text-white transition duration-300 ease-in-out hover:bg-blue-600"
            >
              Add Pessoa
            </button>
          </div>

          <div className="py-10" />

          <h1 className="text-xl font-bold">
            Pessoas que participam do progama:
          </h1>

          <div className="flex flex-col gap-2">
            {pessoas.map((pessoa, index) => (
              <div
                key={index}
                className="flex items-center justify-between rounded border p-2"
              >
                <div>
                  <h2 className="flex gap-2">
                    Nome: <p className="font-bold">{pessoa.nome},</p>{" "}
                  </h2>
                  <h3 className="flex gap-2">
                    Número de vezes no mês:
                    <p className="font-bold">{pessoa.n_vezes}</p>
                  </h3>
                </div>

                <div className="flex gap-2">
                  <button
                    onClick={() => handleDecrementVezes(index)}
                    className="rounded border border-black bg-red-200 p-2 font-semibold"
                  >
                    -1 Vez
                  </button>
                  <button
                    onClick={() => handleIncrementVezes(index)}
                    className="rounded border border-black bg-green-200 p-2 font-semibold"
                  >
                    +1 Vez
                  </button>
                  <button
                    onClick={() => handleDeletePessoa(index)}
                    className="rounded border border-black bg-red-200 p-2 font-semibold"
                  >
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
